# Generated by Django 5.0 on 2024-01-25 18:01

import datetime

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("music_notes", "0002_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="musicnotes",
            name="date_posted",
            field=models.DateTimeField(
                default=datetime.datetime(
                    2024, 1, 25, 18, 1, 42, 765125, tzinfo=datetime.timezone.utc
                )
            ),
        ),
    ]
