# Generated by Django 5.0 on 2024-01-25 18:25

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("music_notes", "0003_musicnotes_date_posted"),
    ]

    operations = [
        migrations.AlterField(
            model_name="musicnotes",
            name="date_posted",
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
    ]
