# Generated by Django 5.0 on 2024-01-28 09:11

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("music_notes", "0004_alter_musicnotes_date_posted"),
    ]

    operations = [
        migrations.AlterField(
            model_name="musicnotes",
            name="duration",
            field=models.DurationField(blank=True, null=True),
        ),
    ]
