# Generated by Django 5.0.2 on 2024-05-26 09:26

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("music_notes", "0006_alter_musicnotes_author"),
    ]

    operations = [
        migrations.AlterField(
            model_name="musicnotes",
            name="notes",
            field=models.FileField(
                blank=True,
                help_text="Pdf file of music notes",
                null=True,
                upload_to="blog/pdf",
            ),
        ),
    ]
