# Generated by Django 5.0 on 2024-01-25 14:27

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("events", "0002_event_participants"),
    ]

    operations = [
        migrations.AddField(
            model_name="event",
            name="time",
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
