# Generated by Django 5.0 on 2024-01-28 09:34

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("events", "0003_event_time"),
    ]

    operations = [
        migrations.AlterField(
            model_name="event",
            name="date",
            field=models.DateField(help_text="date of the event"),
        ),
    ]
