# Generated by Django 5.0 on 2024-01-22 16:26

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("organizations", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="organization",
            name="email",
            field=models.EmailField(blank=True, max_length=50, null=True),
        ),
        migrations.AddField(
            model_name="organization",
            name="phone_number",
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
    ]
