# Generated by Django 5.0.2 on 2024-05-04 18:05

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("organizations", "0002_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="organization",
            name="phone_number",
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
    ]
