# Generated by Django 5.0.2 on 2024-05-04 13:00

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("music_notes", "0002_initial"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterField(
            model_name="musicnotes",
            name="author",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.DO_NOTHING,
                related_name="music_notes",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
        migrations.AlterField(
            model_name="musicnotes",
            name="notes",
            field=models.FileField(
                blank=True,
                help_text="Pdf file of music notes",
                null=True,
                upload_to="pdf",
            ),
        ),
        migrations.AlterField(
            model_name="musicnotes",
            name="voice",
            field=models.CharField(
                blank=True,
                help_text="name of instrument and voice",
                max_length=20,
                null=True,
            ),
        ),
    ]
