# Generated by Django 5.0.2 on 2024-05-04 13:06

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("music_notes", "0003_alter_musicnotes_author_alter_musicnotes_notes_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="musicnotes",
            name="date_posted",
            field=models.DateTimeField(auto_now_add=True),
        ),
    ]
