# Generated by Django 5.0.2 on 2024-05-10 19:01

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("music_notes", "0004_alter_musicnotes_date_posted"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterField(
            model_name="musicnotes",
            name="author",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.DO_NOTHING,
                related_name="created_music_notes",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
    ]
