# Generated by Django 5.0.2 on 2024-05-04 13:00

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("events", "0003_alter_event_repertoire"),
        ("music_notes", "0003_alter_musicnotes_author_alter_musicnotes_notes_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="event",
            name="date_posted",
            field=models.DateTimeField(auto_now_add=True),
        ),
        migrations.AlterField(
            model_name="event",
            name="repertoire",
            field=models.ManyToManyField(
                blank=True,
                help_text="music_notes required for the event",
                null=True,
                to="music_notes.musicnotes",
            ),
        ),
        migrations.AlterField(
            model_name="event",
            name="time",
            field=models.TimeField(
                blank=True, help_text="time of the event", null=True
            ),
        ),
    ]
