# Generated by Django 5.0.2 on 2024-05-10 18:11

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("events", "0004_alter_event_date_posted_alter_event_repertoire_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="event",
            name="place",
            field=models.CharField(max_length=500),
        ),
    ]
